In [5]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [6]:
df=pd.read_csv("train.csv")

In [7]:
df

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117952,1117952,3,3,4,10,4,5,5,7,10,...,7,8,7,2,2,1,4,6,4,0.495
1117953,1117953,2,2,4,3,9,5,8,1,3,...,9,4,4,3,7,4,9,4,5,0.480
1117954,1117954,7,3,9,4,6,5,9,1,3,...,5,5,5,5,6,5,5,2,4,0.485
1117955,1117955,7,3,3,7,5,2,3,4,6,...,6,8,5,3,4,6,7,6,4,0.495
1117956,1117956,4,5,6,9,5,5,2,8,4,...,4,8,6,5,5,6,7,7,8,0.560

In [8]:
df.describe()

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
count,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,...,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06,1.117957e+06
mean,5.589780e+05,4.921450e+00,4.926671e+00,4.955322e+00,4.942240e+00,4.942517e+00,4.934093e+00,4.955878e+00,4.927791e+00,4.942619e+00,...,4.946893e+00,4.953999e+00,4.931376e+00,4.929032e+00,4.925907e+00,4.927520e+00,4.950859e+00,4.940587e+00,4.939004e+00,5.044803e-01
std,3.227265e+05,2.056387e+00,2.093879e+00,2.072186e+00,2.051689e+00,2.083391e+00,2.057742e+00,2.083063e+00,2.065992e+00,2.068545e+00,...,2.072333e+00,2.088899e+00,2.078287e+00,2.082395e+00,2.064813e+00,2.074176e+00,2.068696e+00,2.081123e+00,2.090350e+00,5.102610e-02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.850000e-01
25%,2.794890e+05,3.000000e+00,3.000000e+00,4.000000e+00,4.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,3.000000e+00,3.000000e+00,...,4.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,3.000000e+00,3.000000e+00,4.700000e-01
50%,5.589780e+05,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,...,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.050000e-01
75%,8.384670e+05,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,...,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,5.400000e-01
max,1.117956e+06,1.600000e+01,1.800000e+01,1.600000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.600000e+01,1.600000e+01,1.600000e+01,...,1.700000e+01,1.700000e+01,1.600000e+01,1.600000e+01,1.700000e+01,1.800000e+01,1.900000e+01,1.600000e+01,1.600000e+01,7.250000e-01

In [9]:
df.info

<bound method DataFrame.info of               id  MonsoonIntensity  TopographyDrainage  RiverManagement  \
0              0                 5                   8                5
1              1                 6                   7                4
2              2                 6                   5                6
3              3                 3                   4                6
4              4                 5                   3                2
...          ...               ...                 ...              ...
1117952  1117952                 3                   3                4
1117953  1117953                 2                   2                4
1117954  1117954                 7                   3                9
1117955  1117955                 7                   3                3
1117956  1117956                 4                   5                6

         Deforestation  Urbanization  ClimateChange  DamsQuality  Siltation  \
0                    8             6              4            4          3
1                    4             8              8            3          5
2                    7             3              7            1          5
3                    5             4              8            4          7
4                    6             4              4            3          3
...                ...           ...            ...          ...        ...
1117952             10             4              5            5          7
1117953              3             9              5            8          1
1117954              4             6              5            9          1
1117955              7             5              2            3          4
1117956              9             5              5            2          8

         AgriculturalPractices  ...  DrainageSystems  CoastalVulnerability  \
0                            3  ...                5                     3
1                            4  ...                7                     2
2                            4  ...                7                     3
3                            6  ...                2                     4
4                            3  ...                2                     2
...                        ...  ...              ...                   ...
1117952                     10  ...                7                     8
1117953                      3  ...                9                     4
1117954                      3  ...                5                     5
1117955                      6  ...                6                     8
1117956                      4  ...                4                     8

         Landslides  Watersheds  DeterioratingInfrastructure  PopulationScore  \
0                 3           5                            4                7
1                 0           3                            5                3
2                 7           5                            6                8
3                 7           4                            4                6
4                 6           6                            4                1
...             ...         ...                          ...              ...
1117952           7           2                            2                1
1117953           4           3                            7                4
1117954           5           5                            6                5
1117955           5           3                            4                6
1117956           6           5                            5                6

         WetlandLoss  InadequatePlanning  PoliticalFactors  FloodProbability
0                  5                   7                 3             0.445
1                  3                   4                 3             0.450
2                  2                   3                 3             0.530
3                  5                   7                 5             0.535
4                  2                   3                 5             0.415
...              ...                 ...               ...               ...
1117952            4                   6                 4             0.495
1117953            9                   4                 5             0.480
1117954            5                   2                 4             0.485
1117955            7                   6                 4             0.495
1117956            7                   7                 8             0.560

[1117957 rows x 22 columns]>

In [10]:
column_names = df.columns
print(column_names)

Index(['id', 'MonsoonIntensity', 'TopographyDrainage', 'RiverManagement',
       'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
       'Siltation', 'AgriculturalPractices', 'Encroachments',
       'IneffectiveDisasterPreparedness', 'DrainageSystems',
       'CoastalVulnerability', 'Landslides', 'Watersheds',
       'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss',
       'InadequatePlanning', 'PoliticalFactors', 'FloodProbability'],
      dtype='object')

In [11]:
df.isnull()

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117952,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1117953,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1117954,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1117955,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1117956,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
df = df.replace({False: 1, True: 0})

In [13]:
df

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117952,1117952,3,3,4,10,4,5,5,7,10,...,7,8,7,2,2,1,4,6,4,0.495
1117953,1117953,2,2,4,3,9,5,8,1,3,...,9,4,4,3,7,4,9,4,5,0.480
1117954,1117954,7,3,9,4,6,5,9,1,3,...,5,5,5,5,6,5,5,2,4,0.485
1117955,1117955,7,3,3,7,5,2,3,4,6,...,6,8,5,3,4,6,7,6,4,0.495
1117956,1117956,4,5,6,9,5,5,2,8,4,...,4,8,6,5,5,6,7,7,8,0.560

In [14]:
df.isnull().sum()

id                                 0
MonsoonIntensity                   0
TopographyDrainage                 0
RiverManagement                    0
Deforestation                      0
Urbanization                       0
ClimateChange                      0
DamsQuality                        0
Siltation                          0
AgriculturalPractices              0
Encroachments                      0
IneffectiveDisasterPreparedness    0
DrainageSystems                    0
CoastalVulnerability               0
Landslides                         0
Watersheds                         0
DeterioratingInfrastructure        0
PopulationScore                    0
WetlandLoss                        0
InadequatePlanning                 0
PoliticalFactors                   0
FloodProbability                   0
dtype: int64

In [15]:
df1=pd.read_csv("kerela.csv")

In [16]:
df1.isnull().sum()

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

In [17]:
df1_cleaned = df1.dropna()

In [18]:
df1_cleaned

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,KERALA,2014,4.6,10.3,17.9,95.7,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,3046.4,YES
114,KERALA,2015,3.1,5.8,50.1,214.1,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,2600.6,NO
115,KERALA,2016,2.4,3.8,35.9,143.0,186.4,522.2,412.3,325.5,173.2,225.9,125.4,23.6,2176.6,NO
116,KERALA,2017,1.9,6.8,8.9,43.6,173.5,498.5,319.6,531.8,209.5,192.4,92.5,38.1,2117.1,NO
117,KERALA,2018,29.1,52.1,48.6,116.4,183.8,625.4,1048.5,1398.9,423.6,356.1,125.4,65.1,4473.0,YES

In [19]:
df3=pd.concat([df,df1_cleaned],axis=1)

In [20]:
df3_cleaned = df3.dropna(axis=1)

In [21]:
df3_cleaned

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117952,1117952,3,3,4,10,4,5,5,7,10,...,7,8,7,2,2,1,4,6,4,0.495
1117953,1117953,2,2,4,3,9,5,8,1,3,...,9,4,4,3,7,4,9,4,5,0.480
1117954,1117954,7,3,9,4,6,5,9,1,3,...,5,5,5,5,6,5,5,2,4,0.485
1117955,1117955,7,3,3,7,5,2,3,4,6,...,6,8,5,3,4,6,7,6,4,0.495
1117956,1117956,4,5,6,9,5,5,2,8,4,...,4,8,6,5,5,6,7,7,8,0.560

In [22]:
print(df3_cleaned.columns)

Index(['id', 'MonsoonIntensity', 'TopographyDrainage', 'RiverManagement',
       'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
       'Siltation', 'AgriculturalPractices', 'Encroachments',
       'IneffectiveDisasterPreparedness', 'DrainageSystems',
       'CoastalVulnerability', 'Landslides', 'Watersheds',
       'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss',
       'InadequatePlanning', 'PoliticalFactors', 'FloodProbability'],
      dtype='object')

In [23]:
df3_cleaned = df3.dropna()

In [24]:
df3_cleaned

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,0,5,8,5,8,6,4,4,3,3,...,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,1,6,7,4,4,8,8,3,5,4,...,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,2,6,5,6,7,3,7,1,5,4,...,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,3,3,4,6,5,4,8,4,7,6,...,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,4,5,3,2,6,4,4,3,3,3,...,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,113,4,6,2,5,3,2,11,3,7,...,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,3046.4,YES
114,114,2,9,3,6,5,5,3,3,7,...,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,2600.6,NO
115,115,6,4,6,8,8,4,7,4,10,...,186.4,522.2,412.3,325.5,173.2,225.9,125.4,23.6,2176.6,NO
116,116,3,4,5,6,5,6,3,6,2,...,173.5,498.5,319.6,531.8,209.5,192.4,92.5,38.1,2117.1,NO
117,117,7,4,1,2,7,6,8,5,5,...,183.8,625.4,1048.5,1398.9,423.6,356.1,125.4,65.1,4473.0,YES

In [25]:
feature_columns = [
    'MonsoonIntensity', 'TopographyDrainage', 'RiverManagement', 'Deforestation', 'Urbanization',
    'ClimateChange', 'DamsQuality', 'Siltation', 'AgriculturalPractices',
    'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'
]

In [26]:
X = df3_cleaned[feature_columns]
y = df3_cleaned['FLOODS'].apply(lambda x: 1 if x == 'YES' else 0)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [29]:
model_feature_names = X.columns.tolist()

In [31]:
option = input("Choose an option (1: Predict based on factors (Enter values between 1-10), 2: Predict based on rainfall (Enter values between 1-1000)): ")


if option == '1':
    parameters = {col: float(input(f"Enter {col} ({col}): ")) for col in model_feature_names}
    
    user_data = pd.DataFrame([parameters], columns=model_feature_names)
    
  
    y_pred_proba = model.predict_proba(user_data)[:, 1]  
    y_pred = (y_pred_proba > 0.5).astype(int)  
    
    
    y_pred_label = 'YES' if y_pred[0] == 1 else 'NO'
    
 
    accuracy = accuracy_score(y_test, model.predict(X_test))
    print(f"Accuracy of the model: {accuracy:.2f}")
    print(f"Predicted Floods: {y_pred_label}")

elif option == '2':
    
    rainfall_data = []
    for month in ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']:
        rainfall = float(input(f"Enter rainfall for {month} (0-1000): "))
        rainfall_data.append(rainfall)
    
  
    annual_rainfall = sum(rainfall_data)
    
    
    flood_prediction = 'YES' if annual_rainfall > 3000 else 'NO'
    
    print(f"Flood prediction based on annual rainfall: {flood_prediction}")

else:
    print("Invalid option selected.")

Choose an option (1: Predict based on factors (Enter values between 1-10), 2: Predict based on rainfall (Enter values between 1-1000)): 1
Enter MonsoonIntensity (MonsoonIntensity): 6
Enter TopographyDrainage (TopographyDrainage): 7
Enter RiverManagement (RiverManagement): 9
Enter Deforestation (Deforestation): 7
Enter Urbanization (Urbanization): 8
Enter ClimateChange (ClimateChange): 5
Enter DamsQuality (DamsQuality): 7
Enter Siltation (Siltation): 8
Enter AgriculturalPractices (AgriculturalPractices): 7
Enter JAN (JAN): 8
Enter FEB (FEB): 455
Enter MAR (MAR): 655
Enter APR (APR): 456
Enter MAY (MAY): 345
Enter JUN (JUN): 33
Enter JUL (JUL): 456
Enter AUG (AUG): 778
Enter SEP (SEP): 988
Enter OCT (OCT): 678
Enter NOV (NOV): 455
Enter DEC (DEC): 432
Accuracy of the model: 0.92
Predicted Floods: YES

In [32]:
import pickle

In [33]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)